package algorithms.mazeGenerators;

/**
 * The interface for all maze generators
 */
public interface IMazeGenerator {
    /**
     * @param rows the number of rows in the maze to be generated
     * @param cols the number of columns in the maze to be generated
     * @return the maze object generated by the generate method
     */
    Maze generate(int rows, int cols);

    /**
     * @param rows the number of rows in the maze to be generated
     * @param cols the number of columns in the maze to be generated
     * @return the time in milliseconds it takes to generate the maze with the given params
     */
    long measureAlgorithmTimeMillis(int rows, int cols);
}
